language: node_js
node_js:
  - "10"
  - "12"
  - "13"
install:
  - npm install --save-dev
  - npm install -g jest
  - npm install -g codecov
  - npm install -g codacy-coverage
after_success:
  - codecov
  - codeacy-coverage